version: "3"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
#      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
#      PGPASSWORD: postgres
      POSTGRES_DB: tubuyaita
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data


volumes:
  postgres:

