name: Github Pages
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Setup
        run: npm ci
        working-directory: ./api

      - name: Make
        run: npm run redoc
        working-directory: ./api

      - name: Move files
        run: |
          mkdir -p ./docs/publish/api-schema
          mv ./api/dist/index.html ./docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
